# Generated by Django 3.1.7 on 2021-03-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_messenger', '0007_auto_20210329_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
